### ISSUE TITLE
Excavator can't support 11 gpu or above

### ISSUE THREAD

**Issue by maplerichie** [nicehash/excavator#121] opened 2018-01-17 07:33 UTC
Nicehash miner 2 v2.0.1.8 cannot launch well, then i download excavator alone , v1.3.9a to test, it stop after error:
 CUDA error 'unknown error' in func 'cudahelp::get_device_bus_id_str' line 79
Other miner like Claymore, ethminer, dstm's zm are working well

Build:
12gpus: Nvidia GTX1070
Motherboard: Bisotar TB250BTC Pro
Windows 10 1709
Nvidia Driver 390.65

**Comment by dropky** [comment] 2018-01-17 08:32
Unfortunately, at the moment, we don't have access to a testing rig with 12 gpus (it's on its way :) ). We'll take a look into it then.

**Comment by SergeyKG** [comment] 2018-01-17 13:30
Working ok with 12 x GTX1080Ti but only one algorithm at the same time tested - lyra, neoscrypt, nist5. Any variations lyra+nist5 or nist5+neoscrypt or neoscrypt+lyra crashes Excavator. Can you please make a switch Yes/No different altos at the same time?

**Comment by SergeyKG** [comment] 2018-01-17 22:45
I found a switch named "AllowMultipleInstances" in General.json file. Turned it to false - but no changes, still multiple algos at the same time and then Excavator crash(

**Comment by dropky** [comment] 2018-01-18 07:40
I'll forward this request to the NHM team. 

For now you could try to copy benchmark results from one card to all the others, so that for every card AlgorithmSettings are the same (be careful with that, DeviceUUID shouldn't be overwritten). The NHM should always switch to the same algorithm on all the cards then, since every card should have the same algorithm determined as the most profitable one (based on the same hashrates). Make sure to backup the original benchmark files. Let me know how it goes.

**Comment by SergeyKG** [comment] 2018-01-18 17:24
Thanks for advice!
Began to work more stable. But keeps restarting Excavator if more that one algo allowed to mine. For example when I allow only one algo lyra or nist5 or neoscrypt or other - working absolutely stable! But if I allow two algos or more, for example neoscrypt and lyra, from the very beginning of the first algo running well but when Excavator switches between algos first time after that keeping on restarting in 15-20 sec(. Tried to change minimum timing between switching algos - no changes(
Any ideas what to do? I'm ready to test solution on my rig)

**Comment by dropky** [comment] 2018-01-19 08:56
Can you post here the excavator log file? Add -f 0 parameter to `ExcavatorExtraStartupParameters` in General.json file, restart NHM, wait for the crash, you'll find the logs in `C:\Users\user_name\AppData\Roaming\nhm2\bin\excavator_server\archived_logs`.

**Comment by dropky** [comment] 2018-01-19 09:01
Also you could try to simulate the switch with the next json file. It's switching from neoscrypt to nist5 and then to lyra. Let me know if this causes any problems on your rig.  

```
[
	{"time":0,"commands":[
        {"id":1,"method":"algorithm.add","params":["neoscrypt","neoscrypt.eu.nicehash.com:3341","btc"]}
    ]},
    {"time":1,"commands":[
		{"id":1,"method":"worker.add","params":["0","0"]},
        {"id":1,"method":"worker.add","params":["0","1"]},
		{"id":1,"method":"worker.add","params":["0","2"]},
		{"id":1,"method":"worker.add","params":["0","3"]},
		{"id":1,"method":"worker.add","params":["0","4"]},
		{"id":1,"method":"worker.add","params":["0","5"]},
		{"id":1,"method":"worker.add","params":["0","6"]},
		{"id":1,"method":"worker.add","params":["0","7"]},
		{"id":1,"method":"worker.add","params":["0","8"]},
		{"id":1,"method":"worker.add","params":["0","9"]},
		{"id":1,"method":"worker.add","params":["0","10"]},
		{"id":1,"method":"worker.add","params":["0","11"]}
    ]},
	{"time":10,"loop":15,"commands":[
		{"id":1,"method":"algorithm.print.speeds","params":[]}
	]},
	 {"time":20,"commands":[
        {"id":1,"method":"algorithm.clear","params":[]}
    ]},
	{"time":23,"commands":[
        {"id":1,"method":"algorithm.add","params":["nist5","nist5.eu.nicehash.com:3340","btc"]}
    ]},
	{"time":24,"commands":[
        {"id":1,"method":"worker.add","params":["1","0"]},
        {"id":1,"method":"worker.add","params":["1","1"]},
		{"id":1,"method":"worker.add","params":["1","2"]},
		{"id":1,"method":"worker.add","params":["1","3"]},
		{"id":1,"method":"worker.add","params":["1","4"]},
		{"id":1,"method":"worker.add","params":["1","5"]},
		{"id":1,"method":"worker.add","params":["1","6"]},
		{"id":1,"method":"worker.add","params":["1","7"]},
		{"id":1,"method":"worker.add","params":["1","8"]},
		{"id":1,"method":"worker.add","params":["1","9"]},
		{"id":1,"method":"worker.add","params":["1","10"]},
		{"id":1,"method":"worker.add","params":["1","11"]}
    ]},
	{"time":50,"commands":[
        {"id":1,"method":"algorithm.clear","params":[]}
    ]},
	{"time":53,"commands":[
        {"id":1,"method":"algorithm.add","params":["lyra2rev2","lyra2rev2.eu.nicehash.com:3347","btc"]}
    ]},
	{"time":54,"commands":[
       {"id":1,"method":"worker.add","params":["2","0"]},
        {"id":1,"method":"worker.add","params":["2","1"]},
		{"id":1,"method":"worker.add","params":["2","2"]},
		{"id":1,"method":"worker.add","params":["2","3"]},
		{"id":1,"method":"worker.add","params":["2","4"]},
		{"id":1,"method":"worker.add","params":["2","5"]},
		{"id":1,"method":"worker.add","params":["2","6"]},
		{"id":1,"method":"worker.add","params":["2","7"]},
		{"id":1,"method":"worker.add","params":["2","8"]},
		{"id":1,"method":"worker.add","params":["2","9"]},
		{"id":1,"method":"worker.add","params":["2","10"]},
		{"id":1,"method":"worker.add","params":["2","11"]}
    ]}
]
```

**Comment by SergeyKG** [comment] 2018-01-19 12:02
Hi! It's strange I put -f 0 at ExcavatorExtraStartupParameters and I saw this parameter in command line when Excavator starts. Started with neoscrypt in a wile switched to Blake2s and starting to restart Excavator, but unfortunately no log file at the path(. Folder is empty (for sure folder options are set to view hidden files)

**Comment by SergeyKG** [comment] 2018-01-19 12:04
BTW after restarting Nicehash, Nicehash updates Excavator today, and performs neoscrypt benchmark on all GPUs

**Comment by dropky** [comment] 2018-01-19 12:22
If excavator crashed it's possible that the log file wasn't copied to the archived_logs, in that case the log file should be in the same directory as excavator.exe - `C:\Users\user_name\AppData\Roaming\nhm2\bin\excavator_server\`. Check that dir as well. 

Yes, that's perfectly fine. We released new version of excavator today that included some changes in NeoScrypt (that's why benchmark was needed).

**Comment by SergeyKG** [comment] 2018-01-19 12:51
I have found them there. They are big enougth to publish here, can I send them to email or somewhere else?

**Comment by dropky** [comment] 2018-01-19 12:54
You can send them to support@nicehash.com. Please state in the email that the logs are for excavator team.

**Comment by SergeyKG** [comment] 2018-01-19 12:57
Done!

**Comment by Geesu** [comment] 2018-01-19 15:34
I'm running into the same issue with 10 GPUs, going to forward a log to the above address in case it is helpful as well.

**Comment by Anx2k** [comment] 2018-01-19 16:07
FWIW, the linux verions 1.3.8a  works fine with 13 GPU's - I have several machines running 1070's in that configuration, so probably just the Windows version has the issue.

**Comment by dropky** [comment] 2018-01-19 20:05
@SergeyKG @Geesu Thank you, I got your log files. I'll take a closer look at them asap.

**Comment by Geesu** [comment] 2018-01-19 20:14
If you want to VNC in or anything just reply to my email.

**Comment by SergeyKG** [comment] 2018-01-20 19:06
Today tried to switch to equihash from neoscrypt and Excavator starts to failure. Each 5-10 sec restarting.

**Comment by SergeyKG** [comment] 2018-01-21 18:51
Interesting thing, I started Excavator directly to mine equihash w/o NiceHash with edited command file and it works stable! Looks like API commands from NiceHash makes Excavator restarts every 5-10 sec.

**Comment by maplerichie** [comment] 2018-01-22 10:16
@SergeyKG  You mean you able run 12 GPU directly without Nicehash on Windows? Can share me the configuration step or command?
It fail to launch on both NicehashLegacy and NiceHash2

**Comment by SergeyKG** [comment] 2018-01-22 11:00
You can start Excavator directly w/o NiceHash with -c command (excavator.exe -c config.json) in this case it will be not able to switch the algos in terms on profit. In config file *.json you need to setup your configuration - see bellow - for a rig of 12 GPU's and equihash algo:

[
	{"time":0,"commands":[
		{"id":1,"method":"algorithm.add","params":["equihash","equihash.usa.nicehash.com:3357","YOUR_WALLET.worker1"]}
	]},

	{"time":1,"commands":[
		{"id":1,"method":"worker.add","params":["0","0"]},
        	{"id":1,"method":"worker.add","params":["0","1"]},
		{"id":1,"method":"worker.add","params":["0","2"]},
		{"id":1,"method":"worker.add","params":["0","3"]},
		{"id":1,"method":"worker.add","params":["0","4"]},
		{"id":1,"method":"worker.add","params":["0","5"]},
		{"id":1,"method":"worker.add","params":["0","6"]},
		{"id":1,"method":"worker.add","params":["0","7"]},
		{"id":1,"method":"worker.add","params":["0","8"]},
		{"id":1,"method":"worker.add","params":["0","9"]},
		{"id":1,"method":"worker.add","params":["0","10"]},
		{"id":1,"method":"worker.add","params":["0","11"]}
    	]},

	{"time":10,"loop":10,"commands":[
		{"id":1,"method":"algorithm.print.speeds","params":["0"]}
	]}
]

**Comment by SergeyKG** [comment] 2018-01-22 14:49
@dropky  I saw that new Excavator version was issued today 1.4.1a, but NiceHash did't upgrade it automatically as previous version - should we do it manually?

**Comment by SergeyKG** [comment] 2018-01-22 15:59
@dropky I changed Excavator manually to 1.4.1a but unfortunately still facing restarting. I sent todays log files to the email above. Hope it helps! Please let me know if you need any tests from my side!
@Geesu Did 1.4.1a solved your problems?

**Comment by dropky** [comment] 2018-01-22 19:45
@SergeyKG You're saying, if you switch algorithms with the command line (without NiceHash Miner) everything works fine? Without crashes and it's stable? That's interesting.. 

Regarding the version 1.4.1a - we fixed an issue when Equihash didn't re-connect to the stratum after receiving an invalid response from the server (there were multiple reports regarding this issue). Excavator should be updated automatically yes, but I'm not sure if the new version is already on NH server.  

Thanks for the logs, I'll take a look at them when I get them (it takes some time before the email gets forwarded to me).

**Comment by SergeyKG** [comment] 2018-01-22 19:58
@dropky Yes it's correct looks like NiceHash restarts Excavator. Before update I run Excavator directly w/o NiceHash with equihash and it was stable - no restarts! When I run NiceHash even with only one equihash Excavator begins to restart.

Let me know if I can help with any testings!

**Comment by dropky** [comment] 2018-01-22 20:03
I'm looking at your logs now, hopefully I'll find something. Thank you for all your help so far. I'll let you know if I'll need any more information/feedback.

**Comment by SergeyKG** [comment] 2018-01-22 21:48
One more thing I just saw - when NiceHash is running and I pressed stop button (I stopped mining)(to change mining algos) Excavator continues to restart in 1-2 min.

**Comment by dropky** [comment] 2018-01-23 07:10
@SergeyKG If you disable mining on the primary GPU, do you still encounter this problem? 

Btw, how much virtual memory do you have?

**Comment by SergeyKG** [comment] 2018-01-23 07:46
I tried to disable primary GPU but unfortunately no changes. I have 240GB virtual memory.

**Comment by dropky** [comment] 2018-01-23 12:10
@SergeyKG I looked at your log files and it seems like the restarts are happening due to the bug in NiceHash Miner (when switching to new algorithm). The problem is that new worker is assigned to the device before/without freeing the old one. Unfortunately, there isn't much I can do about it :( I'll report this bug to the NHM team.

**Comment by dropky** [comment] 2018-01-23 12:40
@SergeyKG If you want to I can send you a pre-build of NHM and you can test it out (switching problem should be fixed). Just let me know, I already have your email.

**Comment by SergeyKG** [comment] 2018-01-23 14:17
@dropky Thanks a lot! Yes I'm ok to test pre-build! No problem! If I need to do something special during the tests just give me instructions!

**Comment by Geesu** [comment] 2018-01-23 14:21
If you'd likely me to test as well feel free to shoot it my way. Been running `ethos` on my 13 GPU rig so far as I'm afraid to use NHM.

**Comment by dropky** [comment] 2018-01-23 14:57
@SergeyKG I send you an email. 

@Geesu You're having the same problems on Linux? And you're using standalone Excavator? What happens if you run the config file that I posted in the previous comment - https://github.com/nicehash/excavator/issues/121#issuecomment-358905741 ? If you run only one algorithm on all GPUs is it stable or not?

**Comment by Geesu** [comment] 2018-01-23 15:02
One algo was stable, but it would fail after a few hours due to a switch. Not all cards would stop though, just the ones that switched.

**Comment by SergeyKG** [comment] 2018-01-23 16:51
First results are next - started with Lyra then switched to Neoscrypt then to Nist5 then back to Neoscrypt. All switches was fast w/o Excavator restarts! Running with primary GPU so far no issues. I will wait this night and tomorrow will enable multiple algos at the same time.
@dropky and NHM team Thank you so much for support!!! If you need any additional testings I'm ready to help!

**Comment by dropky** [comment] 2018-01-23 17:04
@SergeyKG Great! This is a really good news :) Thanks again for the feedback!

**Comment by Runningwarrior08** [comment] 2018-01-24 03:45
@dropky It is nice to see that there is a fix for the restarts. They have been plaguing my machine since the last version of NHM2, I have currently been using the legacy version. By chance do you have an estimate on when this new version of excavator will be released?

Thanks!

**Comment by dropky** [comment] 2018-01-24 07:34
@Runningwarrior08 New version of NHM  should be out in the next couple of days (since the issues were caused by NHM and not excavator itself, there is no reason to release a new excavator right now).

**Comment by SergeyKG** [comment] 2018-01-24 07:51
Multiple algos at the same time also running well!!! even with primary GPU on!!! Going to test with motherboard graphics on - to unload GPUs.

**Comment by Nicolas469** [comment] 2018-01-25 02:04
@SergeyKg I also have a rig with with 12 x GTX1080Ti (motherboard:

**Comment by Nicolas469** [comment] 2018-01-25 02:07
@SergeyKG I also have a rig with 12 x GTX1080Ti (motherboard: asrock h110 pro btc+) and I’d like to use NiceHash but windows only sees 10 GPUs (I think this is related to Nvidia drivers because I can see all GPUs when I’m running Ubuntu).
How can you use all your GPUs on Windows ?

**Comment by Runningwarrior08** [comment] 2018-01-25 02:12
@nicolas469 you need the windows 10 fall creator update or greater.

**Comment by Nicolas469** [comment] 2018-01-25 02:20
@SergeyKG Thanks a lot, I’ll try with this update !
Can I ask you your complete rig specs ? (CPU, Mothboard, RAM, Virtual Memory Size or any other Windows tweaks to get NiceHash working stabely without the constant restart...) Thanks a lot for your answer, it’d be very helpful for me =)

**Comment by maplerichie** [comment] 2018-01-25 05:05
@SergeyKG 
I follow ur configuration above but still have issue
`
=========================== www.nicehash.com =========================
           Excavator v1.4.0a_nvidia GPU Miner for NiceHash.
           Copyright (C) 2017 NiceHash. All rights reserved.
                              Developed by
                djeZo, dropky, voidstar, and agiz
                   with help and contributions from
           zawawa, pallas, Vorksholk, bitbandi, ocminer, and Genoil.
=========================== www.nicehash.com =========================

Build time: 2018-01-18 17:01:45
Build number: 4368
Provided startup commandline:
        "C:\ethminer\excavator\excavator.exe" -c .\config.json

[13:04:42][0x0000aba8][info] Log started
[13:04:43][0x0000aba8][info] core | Found CUDA device: GeForce GTX 1070
[13:04:43][0x0000aba8][error] CUDA error 'unknown error' in func 'cudahelp::get_device_bus_id_str' line 79
`

**Comment by Nicolas469** [comment] 2018-01-25 10:14
@SergeyKG I’ve got this:
Windows Specs:
Edition: Windows 10 Family
Version: 1709
OS Version: 16299.192

So I already have Windows Fall Upgrade (it’s the version 1709 of Windows, right ?).
Do I need Windows Pro instead of family ?

**Comment by SergeyKG** [comment] 2018-01-25 11:55
@Nicolas469, I use ASUS B250 Mining Expert - Windows sees - 12 GPU's. But I'm using Windows Pro

**Comment by SergeyKG** [comment] 2018-01-25 11:58
Configuration is: CPU i5-7400@3.00Ghz, RAM 8GB, 240GB virtual memory, last nvidia driver 390.65

**Comment by dropky** [comment] 2018-01-25 12:20
NHM (Version 2.0.1.9) with "Improved excavator state handling (improved stability)" has been released - https://miner.nicehash.com/ .

**Comment by Runningwarrior08** [comment] 2018-01-25 14:01
@dropky Thank you very much! Running it now. I will let you know if I see any issues.

**Comment by Nicolas469** [comment] 2018-01-25 22:14
@SergeyKG Thanks =)
If you use a B250, why don't you use more than 12 GPUs ?
I've bought windows 10 Pro and now Windows can see all of my 13 1080ti !
But NiceHash doesn't seems to work when I'm using 13 GPUs (but works well with 12)...
Any suggestion ?

**Comment by SergeyKG** [comment] 2018-01-26 06:51
@Nicolas469 Currently I have only 12 GPU’s. Little bit later I will test 12+. When I was running 10 GPU’s and added another 2 couple of windows restarts helped me.

**Comment by Nicolas469** [comment] 2018-01-28 13:55
This night I’ve got this with my 12x 1080ti:
https://ibb.co/hF2wBw
It seems that NiceHash has stopped working for time to time for no reason...
Any guess ? Lack of virtual memory ?
(I don’t think I’ve had this problem with only 9 GPUs)

**Comment by dropky** [comment] 2018-02-15 11:26
I'm closing this since NHM v2.0.1.9 solved this issue https://github.com/nicehash/excavator/issues/121#issuecomment-360451069

**Closed by dropky** 2018-02-15 11:26 UTC
Labels: bug, enhancement

**Comment by samywee** [comment] 2018-03-01 06:24
I am running 2.0.1.11 and NHM crash from time to time. I don't see a directory 

C:\Users\user_name\AppData\Roaming\nhm2\bin\excavator_server\archived_log

Where can I find the log that I see on console. (I see an error on console in RED, but quickly disappear and restart the NHM before I can read the log.)

C:\Users\user_name\AppData\Roaming\nhm2\logs - is not the same log that I see on the console

Crashes/restarts are common when I enable all Algorithms. When I reduce them to a single Algorithm, I don't see the crashes / restarts of the NHM.

**Comment by dropky** [comment] 2018-03-01 08:05
@samywee To enable excavator file logging you'll have to add -f 0 parameter to ExcavatorExtraStartupParameters in nhm2\configs\General.json file. Restart NHM and you'll find the logs in the excavator_cuda9.1 directory (after some time).
