### ISSUE TITLE
Miner crashing on CUDA error DRIVER: 2 in func 'cuda_eq_cubin_init

### ISSUE THREAD

**Issue by michalss** [nicehash/excavator#209] opened 2018-03-06 17:24 UTC
Miner crashing on this, pls help

![image](https://user-images.githubusercontent.com/1000729/37047534-85b18ce8-216b-11e8-975f-934b570398e0.png)

**Comment by dropky** [comment] 2018-03-08 20:21
Your driver is crashing, check your overclock settings. If you run excavator on stock settings, does it still crashes?

**Comment by GrossoMoreira** [comment] 2018-03-13 20:15
Hi,

I've been getting the same issue using the 2 latest versions of NiceHash miner (clearly the problem is in excavator though).

**I didn't do any kind of overclocking.**

Using a GTX 1070 on windows 7.

**Comment by dropky** [comment] 2018-03-14 12:36
How many GPUs do you have? What power supply are you using? Driver version? Does it always crash on equihash?

**Comment by GrossoMoreira** [comment] 2018-03-14 19:25
The GTX 1070 (no OC) is the only GPU installed.
OS: Windows 7
CPU: i7 7700K
RAM: 16GB
Power supply: Corsair 1000W
Driver: 391.01 (I updated to the latest version because of these crashes but they keep happening)

It crashes on equihash, but also on lyra and dagger_hashimoto. Haven't tested others.

The error mentioned by the OP is not the only one I get. I also see something similar to 'Invalid memory access error'. Maybe they are two different problems though.

**Comment by nicehashdev** [comment] 2021-01-07 07:31
This algorithm is not supported anymore. Closing

**Closed by nicehashdev** 2021-01-07 07:31 UTC
