### ISSUE TITLE
Unable to add worker with debug level 5, 4, 3

### ISSUE THREAD

**Issue by nirvanaosc** [nicehash/excavator#40] opened 2017-07-16 16:44 UTC
I started excavator using debug level 5 (excavator.exe -na -d 5 -p 5000 -wp 6000 -wi 127.0.0.1) and I was unable to add a worker. I was getting the following error when trying to add a worker for equihash:

[17:31:41][0x00001ff8][fatal] wrkr0-1 | CUDA error 'invalid argument' in func 'cuda_eq_run' line 2356
[17:31:41][0x00000d00][fatal] wrkr0-0 | CUDA error 'invalid argument' in func 'cuda_eq_run' line 2356
[17:31:41][0x00001238][fatal] wrkr1-2 | CUDA error 'invalid argument' in func 'cuda_eq_run' line 2356

and this is the error when trying to add a worker for blake2s:

[17:33:35][0x00002300][fatal] wrkr0-0 | CUDA error 'invalid argument' in func 'cuda_blake2s::run' line 546
[17:33:35][0x000018d8][fatal] wrkr1-1 | CUDA error 'invalid device pointer' in func 'cuda_blake2s::deinit' line 458
[17:33:35][0x00001134][fatal] wrkr7-7 | CUDA error 'invalid device pointer' in func 'cuda_blake2s::deinit' line 458

I didn't try other algorithms.
Happens the same with debug levels 4 and 3. Also, debug level 6 seems to be the same as 0.

If you need anything else from me please let me know.

**Comment by nicehashdev** [comment] 2017-07-16 16:47
We were unable to reproduce your issue by just setting debug console level. Could you also share your command file?

**Comment by nicehashdev** [comment] 2017-07-16 16:48
Your issue looks like a crashed driver that needs system reboot. Have you tried that?

**Comment by nirvanaosc** [comment] 2017-07-16 17:02
I did now. It still happens.

**Comment by nirvanaosc** [comment] 2017-07-16 17:03
I will try to get a list with the commands to reproduce this issue.

**Comment by nirvanaosc** [comment] 2017-07-16 17:10
Executing the following command reproduces the issue:

excavator.exe -na -d 5 -p 5000 -wp 6000 -wi 127.0.0.1 -c file.json

with file.json containing:
[
	{"time":1,"commands":[
		{"id":1,"method":"algorithm.add","params":["equihash","equihash.eu.nicehash.com:3357","34HKWdzLxWBduUfJE9JxaFhoXnfC6gmePG.testrig"]}
	]},
	{"time":2,"commands":[
		{"id":1,"method":"worker.add","params":["0","1"]},
		{"id":1,"method":"worker.add","params":["0","1"]},
		{"id":1,"method":"worker.add","params":["0","2"]},
		{"id":1,"method":"worker.add","params":["0","2"]},
		{"id":1,"method":"worker.add","params":["0","3"]}
	]}
]

I am using NVIDIA drivers 384.76

**Comment by nirvanaosc** [comment] 2017-07-16 17:11
It works with debug level 0, 1, 2 and 6 (but 6 seems the same as 0)

**Comment by nicehashdev** [comment] 2017-07-17 18:10
Can you try with some older driver version?

What happens if you add only certain device and not all?

**Comment by nicehashdev** [comment] 2017-07-19 10:53
No response anymore, closing.

**Comment by nirvanaosc** [comment] 2017-07-19 10:59
Sorry, I am away for one week and I don't have access to my hardware.
I will try once I am back and I will report back to you.

**Comment by nirvanaosc** [comment] 2017-07-25 19:13
Hello,

I'm back and I tested what you suggested.
Drivers 378.78 (the oldest drivers I could get) behaves exactly the same. These drivers are 4 months old.
Also, I tried adding only one worker to the first device with the json file:

[
{"time":1,"commands":[
{"id":1,"method":"algorithm.add","params":["equihash","equihash.eu.nicehash.com:3357","34HKWdzLxWBduUfJE9JxaFhoXnfC6gmePG.testrig"]}
]},
{"time":2,"commands":[
{"id":1,"method":"worker.add","params":["0","0"]}
]}
]

and I got the error

[20:12:02][0x00001950][fatal] wrkr0-0 | CUDA error 'invalid argument' in func 'cuda_eq_run' line 2356

Using the command line

excavator.exe -na -d 5 -p 5000 -wp 6000 -wi 127.0.0.1 -c file.json

If you need anything else from me please let me know.
Regards.

**Comment by nicehashdev** [comment] 2017-07-25 19:20
Could you also share with us what kind of cards do you use?

**Comment by nirvanaosc** [comment] 2017-07-25 19:23
This rig has 8x ASUS GTX 1080 Ti Founders Edition

**Comment by nicehashdev** [comment] 2017-07-25 19:31
Let me make this clear, when you change -d 5 to -d 2 and NOTHING else, it works just fine?

**Comment by nirvanaosc** [comment] 2017-07-25 19:38
That is correct.

**Comment by nicehashdev** [comment] 2017-07-25 19:50
What happens if you unplug 7 cards and leave just 1 inside?

**Comment by nicehashdev** [comment] 2017-07-25 19:51
And does it happen for all algorithms or only equihash?

**Comment by nirvanaosc** [comment] 2017-07-25 19:52
I was happening the same with blake2s. I didn't try the others.

**Comment by nirvanaosc** [comment] 2017-07-25 19:53
Let me try with just one card.

**Comment by nirvanaosc** [comment] 2017-07-25 19:58
Yes, it happens the same with 1 GPU. This GPU is not using a riser.

**Comment by nicehashdev** [comment] 2017-07-25 20:14
Got it now. Fixed in next ver.

**Comment by nirvanaosc** [comment] 2017-07-25 20:14
That's good news. Glad to help.

**Comment by nicehashdev** [comment] 2017-07-28 19:19
This has been fixed in latest version.

**Closed by nicehashdev** 2017-07-28 19:19 UTC
Labels: bug
