### ISSUE TITLE
GTX 1070  - Version 1.3.8 alpha neoscrypt not work

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/excavator#78] opened 2017-11-24 14:18 UTC
`[17:11:24][0x00001518][info] Log started
[17:11:25][0x00001518][info] core | Found CUDA device: GeForce GTX 1070
[17:11:25][0x00001518][info] core | Found CUDA device: GeForce GTX 1070
[17:11:25][0x00001518][info] core | Found CUDA device: GeForce GTX 1070
[17:11:25][0x00001518][info] core | Found CUDA device: GeForce GTX 1070
[17:11:25][0x00001518][info] core | Found CUDA device: GeForce GTX 1070
[17:11:25][0x00001518][info] api | Listening on 0.0.0.0:33333
[17:11:25][0x00001518][info] http | Listening on 0.0.0.0:38080
[17:11:25][0x00001518][info] core | Initialized!
[17:11:26][0x00002300][info] net | Connecting to 169.50.175.203:3341 (neoscrypt.eu.nicehash.com)
[17:11:26][0x00002300][info] net | Connected!
[17:11:26][0x00002300][info] net | Authorized as 19M9g3vvfyDfUhdekwokAVanKdiTtSCmF2.node07
[17:11:26][0x00002300][info] algo-neoscrypt | New job_0 '000000096d78dbc0', diff=0.0078125
[17:11:28][0x00000774][info] wrkr1-1 | Algorithm: CUDA-neoscrypt parameters: B=1410
[17:11:29][0x00002b8c][info] wrkr3-3 | Algorithm: CUDA-neoscrypt parameters: B=1410
[17:11:29][0x00000d58][info] wrkr2-2 | Algorithm: CUDA-neoscrypt parameters: B=1410
[17:11:29][0x00002008][info] wrkr0-0 | Algorithm: CUDA-neoscrypt parameters: B=1410
[17:11:29][0x00002814][fatal] wrkr4-4 | CUDA error 'out of memory' in func 'cuda_neoscrypt::init' line 1258
[17:11:29][0x00001518][info] Shutting down
[17:11:30][0x00001518][info] api | Closing
[17:11:30][0x00001518][info] http | Closing`

Overclocking disabled : 
{"id":1,"method":"device.set.tdp","params":					["0","100"]},
{"id":1,"method":"device.set.core_delta","params":	["0","0"]},
{"id":1,"method":"device.set.memory_delta","params":["0","0"]},

**Comment by Kayfolom** [comment] 2017-11-24 14:32
on GTX 1080 - system crash.
At GTX 1080Ti I will not try so far - is it not enough that ...

**Comment by dropky** [comment] 2017-11-24 14:46
Are you running anything else on your cards beside excavator? That would explain the 'out of memory' error. You can try to decrease the B parameter, the size of memory needed to run will decrease as well.  Let me know how it goes. 

Also, could you please post here config file? Thanks.

**Comment by Kayfolom** [comment] 2017-11-24 15:44
Only the excavator has been launched, no other miners or applications
`[
	{"time":1,"commands":[
		{"id":1,"method":"algorithm.add","params":["neoscrypt","neoscrypt.eu.nicehash.com:3341","19M9g3vvfyDfUhdekwokAVanKdiTtSCmF2.node07"]}
	]},
	{"time":2,"commands":[
		{"id":1,"method":"worker.add","params":["0","0"]},
		{"id":1,"method":"worker.add","params":["0","1"]},
		{"id":1,"method":"worker.add","params":["0","2"]},
		{"id":1,"method":"worker.add","params":["0","3"]},
		{"id":1,"method":"worker.add","params":["0","4"]}
	]},
	{"time":5,"commands":[
		{"id":1,"method":"device.set.tdp","params":					["0","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["0","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["0","0"]},
		{"id":1,"method":"device.set.tdp","params":					["1","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["1","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["1","0"]},
		{"id":1,"method":"device.set.tdp","params":					["2","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["2","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["2","0"]},
		{"id":1,"method":"device.set.tdp","params":					["3","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["3","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["3","0"]},
		{"id":1,"method":"device.set.tdp","params":					["4","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["4","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["4","0"]}
	]},
{"time":10,"commands":[
		{"id":1,"method":"worker.reset","params":["0"]},
		{"id":1,"method":"worker.reset","params":["1"]},
		{"id":1,"method":"worker.reset","params":["2"]},
		{"id":1,"method":"worker.reset","params":["3"]},
		{"id":1,"method":"worker.reset","params":["4"]},
		{"id":1,"method":"worker.reset","params":["5"]},
		{"id":1,"method":"worker.reset","params":["6"]},
		{"id":1,"method":"worker.reset","params":["7"]},
		{"id":1,"method":"worker.reset","params":["8"]},
		{"id":1,"method":"worker.reset","params":["9"]}
	]},
	{"time":15,"loop":20,"commands":[
		{"id":1,"method":"worker.print.speed","params":["0"]},
		{"id":1,"method":"worker.print.speed","params":["1"]},
		{"id":1,"method":"worker.print.speed","params":["2"]},
		{"id":1,"method":"worker.print.speed","params":["3"]},
		{"id":1,"method":"worker.print.speed","params":["4"]},
		{"id":1,"method":"worker.print.speed","params":["5"]},
		{"id":1,"method":"worker.print.speed","params":["6"]},
		{"id":1,"method":"worker.print.speed","params":["7"]},
		{"id":1,"method":"worker.print.speed","params":["8"]},
		{"id":1,"method":"worker.print.speed","params":["9"]},
		{"id":1,"method":"algorithm.print.speeds","params":["0"]}
	]},
	{"event":"on_quit","commands":[
		{"id":1,"method":"device.set.tdp","params":					["0","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["0","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["0","0"]},
		{"id":1,"method":"device.set.tdp","params":					["1","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["1","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["1","0"]},
		{"id":1,"method":"device.set.tdp","params":					["2","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["2","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["2","0"]},
		{"id":1,"method":"device.set.tdp","params":					["3","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["3","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["3","0"]},
		{"id":1,"method":"device.set.tdp","params":					["4","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["4","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["4","0"]}
	]}
]
`

Stable earned only with parameters "worker.add","params":["0","0","B=1230"]

And a very large consumption of computer RAM (Not GPU RAM) - at the start of the miner is 500 megabytes. And after the start, the memory consumed is reduced by 1 megabyte per second. Several mines passed and consumed memory of 216 megabytes.

**Comment by dropky** [comment] 2017-11-24 16:27
This doesn't seem ok. Which version of drivers are you using? I will try to reproduce the problem on my machine. 

FYI. You're resetting workers that don't even exists. You have 5 workers (not 10).

**Comment by Kayfolom** [comment] 2017-11-24 17:55
Win 10 Pro 64bit, nvidia driver 382

> FYI. Вы перезагружаете работников, которых даже нет. У вас 5 рабочих (не 10).
Yes, I forgot ... Config copied from another file, fixed the worker, and forgot the worker reset ... But it could not affect - the excavator is smart enough to reset the non-existent workers ;-)

**Comment by Kayfolom** [comment] 2017-11-24 18:03
Try GTX 1080 Ti - all fine :

`21:01:37][0x000006a4][info] core | Algorithm 'neoscrypt' total speed: 1.111407 MH/s
21:01:43][0x00000870][info] net | Share #10 accepted
21:01:45][0x00000870][info] algo-neoscrypt | New job_0 '0000000c8bebcf44', diff=0.00390625
21:01:46][0x000006a4][info] net | Share #11 accepted
21:01:57][0x000006a4][info] core | Device #0-0 speed: 1.101545 MH/s
21:01:57][0x000006a4][info] core | Algorithm 'neoscrypt' total speed: 1.106978 MH/s
21:02:17][0x00000870][info] core | Device #0-0 speed: 1.101532 MH/s
21:02:17][0x00000870][info] core | Algorithm 'neoscrypt' total speed: 1.104563 MH/s
21:02:34][0x00000870][info] net | Share #12 accepted
21:02:37][0x000006a4][info] core | Device #0-0 speed: 1.100956 MH/s
21:02:37][0x000006a4][info] core | Algorithm 'neoscrypt' total speed: 1.103118 MH/s
21:02:42][0x000006a4][info] algo-neoscrypt | New job_0 '0000000c8bebe7bf', diff=0.00390625`

**Comment by UselessGuru** [comment] 2017-11-26 09:23
Try GTX 1080 Ti - all fine.
But unfortunately nowhere near as fast as Ccminer-KlausT

**Comment by dropky** [comment] 2017-11-26 09:24
We're still working on optimisations, especially for 1080 and 1080 ti cards. We'll release an update soon.

**Comment by kgiedrius** [comment] 2017-11-27 09:37
works fine for me on 1070cards with newest nvidia drivers

**Comment by ebbbang** [comment] 2017-12-03 16:25
Not working for me as well on both my rigs ...
Same issue as described in the first post ...

**Comment by dropky** [comment] 2017-12-03 17:17
@ebbbang driver version? Which cards do you have?

**Comment by obit8** [comment] 2017-12-03 19:59
Good evening guys, i have the same problem some times.

This is my configuration:
ASUS B250 MINING EXPERT Intel B250 LGA 1151 (Socket H4) ATX motherboard - motherboards (DDR4-SDRAM, DIMM, 2133,2400 MHz, Dual, 32 GB, Intel)

18 x - GTX 1060 3gb MSI gamingx 
1 x - CPU intel Pentium G4400 LGA1151 
3 x - Alimentatore Cooler master V1000 
1 x - 16gb DDR4 2400mhz Hyper x fury 
1 x - 120gb ssd (kingston adata) 
1 x - custom rack mining

I'm working with only 11 GPU and 2 Power supply, because the driver on the mobo doesn't allow, for now, 18 card of the same kind.

I put an image of the error i receive sometimes, at least any 340/400 net share accepted (this is the only unit i can see to give you an element to understand how many times i get that error)

It is ok to receive it sometimes or not?
And my RAM is ok or i need more?
<img width="1440" alt="schermata 2017-12-03 alle 20 49 23" src="https://user-images.githubusercontent.com/2878760/33529157-db6f4334-d86c-11e7-9978-dbe1d095724c.png">

**Comment by dropky** [comment] 2017-12-04 07:43
@obit8 It's definitely not ok to get this error. We're working on it. Thanks for the info.

**Comment by obit8** [comment] 2017-12-04 08:37
@dropky my card is a 1060 msi nvidia.

Some times this error shows up

**Comment by dropky** [comment] 2017-12-04 08:39
@obit8 driver version?

**Comment by kgiedrius** [comment] 2017-12-04 13:08
Can't it be the problem that sometimes algorithms use > 5GB of GPU memory and your card have only 3GB ?

**Comment by kgiedrius** [comment] 2017-12-04 13:09
I personaly use excavator on ubuntu with gtx 1070 cards and never saw similar issues

**Comment by dropky** [comment] 2017-12-04 13:59
@kgiedrius  Neoscrypt requires quite a lot of memory, on 1070 cards it's 5GB, on other cards it's less than that (usually allocates around 70% of the GPU's memory). The cuda 'out of memory' error happens because at the moment there isn't enough free memory on the GPU, the system might be using it (primary cards) or something hasn't been freed completely yet (nhm2 switching). We're working on a way around - if there won't be enough free memory the block parameter will be modified (the intensity will be decreased for a bit).  

**Note for everyone:** 
Make sure you're running only one worker per card!
In some cases this problem was solved with updating windows drivers.

**Comment by obit8** [comment] 2017-12-04 17:35
Driver versione 388.4

However now i see that the escavator reboot frequently! Also without any CUDA memory error!...

There is something i can do to solve this?

**Comment by obit8** [comment] 2017-12-05 17:05
@Kayfolom i've disabled the neoscrypt from the config file!

Is just annoying that you need to edit every single gpu file! But at the End the excavator started the work without error mining the "Lyra2Rev2"...

Today it worked well for me for almost 10 hours with CryptoNight and Equihash...then i see 0 worker online and when i checked i saw that it continued to give me the CUDA MEMORY error trying to mine the neoscrypt!
<img width="1440" alt="schermata 2017-12-05 alle 17 43 43" src="https://user-images.githubusercontent.com/2878760/33619979-dcba0316-d9e6-11e7-8118-6e1d6ccd9361.png">

**Comment by OlArMiners** [comment] 2017-12-05 22:42
Same problem.... 
![1070 nicehash](https://user-images.githubusercontent.com/34287727/33634585-5bab7cd2-da1d-11e7-821e-5fae41f0a1d0.png)
8x1070 Palit

8 Gb RAM
32Gb Swap

When switching to "neoscrypt" - go to Error 'out of memory' and endless restart

So i Reboot.... and it working fine whith Algorithm 'equihash'..... for now....

**Comment by Pititul** [comment] 2017-12-07 08:24
Got the same 'out of memory'.

**Comment by obit8** [comment] 2017-12-07 08:41
Well, for Now al is gone with nicehash.
Al BTC Wallet easy stolen.

I’m looking for another altcoin. ;(
Il giorno gio 7 dic 2017 alle 09:24 Meeh <notifications@github.com> ha
scritto:

**Comment by hapklaar** [comment] 2017-12-19 19:46
Is this issue still on the radar now Nicehash is down? Have the same memory errors on my dual GTX1070 setup.

**Comment by dropky** [comment] 2017-12-21 12:18
@hapklaar Yes, it is :)

**Comment by nlaciii** [comment] 2017-12-21 17:04
I assume this is not a common scenario yet, but I have a rig with 13xGTX1070 and 4xP106-100 Nvidia GPUs. Before Dec 5. it was running only the 13x1070-s, and with that config NHM2 and excavator was running perfectly stable. Now with the P106-100-s (6GB) I'm getting this same CUDA error, out of memory. Also some other crashes without noticable error message.
On my other rigs with 4x1070 and 4x1060(or P106-100) 6GB, everything running fine.

Win10 1709, Nvidia driver 388.43, - and with all fairness all ccminer incarnations also have the same problem with neoscrypt and lyra2rev2
EWBF, DSTM, and CLaymore's eth miners are perfectly stable running on all the GPUs.
I can provide you logs, or even access to the rig for testing if needed.

**Comment by diwu1989** [comment] 2017-12-25 18:32
One of my miner just hit this issue too, had to restart NiceHash in the morning and missed out on 6 hours of mining.

Please do one of the following:
- investigate and fix this memory bug
- take neoscrypt out of Nvidia cards for now until its stable
- add code to detect memory failure and auto-restart in that case vs be stuck in the failed state

**Comment by jlavyan** [comment] 2017-12-26 08:45
I have Same error
RAM 8GB, Virtual memory 20GB - 25GB, Windows 10 
Nicehash 2.0.1.5

**Comment by bviktor** [comment] 2017-12-29 01:48
To me it happens on a 1080 too. Even if I run nothing else, and simply try to start a single excavator on a single GPU. And it fails right away. Seems like a problem with parameters or extremely screwed up memory allocation, if I had to guess.

**Comment by Tottom** [comment] 2017-12-30 07:18
Hi,
Same issue for me on GeForce GTX 6x 1070 and 2x 1070Ti, CUDA 9.1.85, Nvidia 388.71
CUDA error 'out of memory' in func 'cuda_neoscrypt::init' line 1258

**Comment by SergeyKG** [comment] 2018-01-01 01:49
Hi all and Happy New Year!!!
Have a problem running NiceHash Miner 2.0.1.5 with 11x 1080ti 65% +50 +100
Stable I can run only lyra2rev2 any other algo-s runs for 15-30 seconds and then excavator restarts. I turned off all algo-s except lyra2rev2 to work stable with NiceHash Miner. Tried with 65% +0 +0 - same issue. If I run the same algos with ccminer no crushes - works fine.

**Comment by Tottom** [comment] 2018-01-01 07:07
Hi. 
How much physical memory and virtual (pagefile) memory do you have if you are running Windows?

Also refer to this thread.
Nicehash v2.0.1.3 out of memory Issue still "nicehash/NiceHashMiner2"
sorry, not sure how to reference it...

Seems there might also be a fix on the way.

**Comment by SergeyKG** [comment] 2018-01-01 08:04
Hi Tomtom,

I have 8GB RAM and 40GB virtual memory.

**Comment by SergeyKG** [comment] 2018-01-01 08:04
Hi Tottom!

I have 8GB RAM and 40GB virtual memory.

**Comment by SergeyKG** [comment] 2018-01-01 11:16
Just checked RAM loading under Lyra2rev2 and Equihash, interesting effect - Lyra2rev2 loads the RAM up to 48% (3.8GB) and works ok. When running Equihash it runs ok several seconds before the RAM load reaches 50%+ (4GB) and then Excavator restarts. I raised virtual memory to 80Gb but unfortunately Excavator continues to restart.

**Comment by M1r00** [comment] 2018-01-01 18:52
Hi, I am experiencing the same issue of running out of memory especially with neoscrypt algorythm on one of my rigs .
I got two rigs with 
     6* GTX 1070 each, 1st one 1 Aorus + 5 * G1 
     MSI H270 A pro with latest bios
     12GB ram  
     CPU  G3950 (7th gen)
      2* cooler master V750 
      primary graphic card is on the intel HD 630
      Windows 10 x64 pro ver 1709
      nvidia driver 384.76
The second rig is the exact same except for 
     Strix gpu instead of G1
     CPU G3900 (6th Gen)

The first rig is working perfectly without any issue even with neoscrypt ( take appart if I run the 6 gpu on neoscrypt it crashes after minutes). the second rig (the strix) is stop working using neoscrypt on nicehash 2.0.1.5 with only two gpus mining in neoscrypt.

i will try to clone the G1 OS and run the strix with it to see if the problem is due to software problems cause seems weird that the two rigs aren't behaving the same way

**Comment by Tottom** [comment] 2018-01-01 20:27
So the 11x 1080ti cards has 11GB mem each? 

My 8x 1070 has 8GB each. at 64GB vRAM it was still giving issues.
After changing it to 96GB it seems to be stable now for almost 32 hours.
Could have been less vRAM needed but easy to set without worrying about the failure again.

Now also fixed on mining only Lyra2rev2, Equihash and Blake2s.
Best profit from those 3 for me.

**Comment by SergeyKG** [comment] 2018-01-01 21:29
Understood your point! Thanks a lot!
Unfortunately my SSD has only 120GB. To map 11x11GB I need at least 121GB and it means that I need to change SSD.
You are right 11x 1080ti has 11GB each.

**Comment by Tottom** [comment] 2018-01-02 07:34
How long before the excavator restarts? Maybe you can keep the 80GB vRAM and enable 6 cards, then 7 and then more to see how long it before it becomes unstable? Last night i started see the excavator restarting. so it seems the garbage collection is not clearing the vRAM efficiently and when i restarted the Rig, the excavator started and has been running since without the same issue. so i guess i have to restart the Rig every 24 to 30 hours...

**Comment by Tottom** [comment] 2018-01-02 07:38
M1r00, what vMEM have you set for each your Rigs. Since you have 2x Rigs with 6x 1070. I have 8x 1070(2 of them ti) and had tried it with 64GB vMEM and it still gave me Out of Memory... So i changed it to 80GB and it was stable for just over 32hours. If you are on 16GB or 32GB vMEM then make it 48GB or 64GB. see how it runs then?

**Comment by obit8** [comment] 2018-01-02 07:41
In my case if i disable all the algo exept one the miner is stable, if i enable 2 or more the miner continue to restart!

I have x13 1060...

Now i'm only mining lyr2v2, and when i see it on whattomine i change with Equihash!!!

**Comment by Tottom** [comment] 2018-01-02 07:51
here is my current config. Running Lyra2rev2, NeoScrypt, EquiHash and Blake2b. Depending on the profitability as you mentioned on WhatToMine. Maybe it is just my Rig but this works for me. I i add 2 more cards, i might run into the same issue again or maybe not.

![miner1](https://user-images.githubusercontent.com/26551123/34477363-553947ae-efa2-11e7-83bc-059430708c21.PNG)
![miner2](https://user-images.githubusercontent.com/26551123/34477364-556c5482-efa2-11e7-932f-ba781fa0dea4.PNG)
![miner3](https://user-images.githubusercontent.com/26551123/34477365-559fee00-efa2-11e7-9015-eb9cc025c0ba.PNG)

**Comment by SergeyKG** [comment] 2018-01-02 08:12
Before I got to 11x 1080ti I run 7 of them and Excavator worked stable (several days without issues) on any algo even with 2-3 algos at the same time.
With 11 cards it restarts in 30-60 seconds (working stable only on Lyra2rev2)
Later today will try to expand virtual memory to 256GB and see what happens.

**Comment by Tottom** [comment] 2018-01-02 08:22
Don't think 256GB is what you should set it rigt now. 
Try 128GB then Level up 32GB till stable.
Good luck!

**Comment by M1r00** [comment] 2018-01-02 08:24
I am setting 20 GB for each.  my ssd is 120gb and still have 30gb free on my ssd so I assume I can go to 40GB. But my G1 rig is rock stable with 20 GB unlike the strix.

**Comment by Tottom** [comment] 2018-01-02 08:44
might be some app config perhaps. what version of excavator are you running?

**Comment by M1r00** [comment] 2018-01-02 08:48
Using nicehash 2.0.1.5...tried multiple drivers 384.76 then 388.31....the G1 is running stable with the 384.76 ....will post screenshots when @ home

**Comment by SergeyKG** [comment] 2018-01-02 15:16
Tried 128GB and then +32GB up to 244GB unfortunately only Lyra2rev2 stays stable, at Equihash Excavator still restarting.

**Comment by Tottom** [comment] 2018-01-02 15:33
That is unfortunate. 
Not sure then why it is failing still... if not memory then power / driver / excavator? 

I am running nVidia driver: 388.71

Excavator_Server 1.38 - https://github.com/nicehash/excavator/releases
I downloaded it and pasted it in my own NH2 folder.

Apart from the above, i am at a loss why you are experiencing the issue :(

**Comment by SergeyKG** [comment] 2018-01-03 07:34
Running the same versions driver and Excavator - will keep on digging)
Thanks for support!

**Comment by reproteq** [comment] 2018-01-10 21:51
I had the same problem when I was mining neoscrypt 
and solve it like that:
format and reinstall all drv nvidia and gigabyte oc soft. and nicehash last version.
oc gigabyte soft alls gpus -20% power
open nicehash soft and make normal benchmark
now all it is working perfect , i can miner neoscrypt without errors cuda

solved
CUDA error 'out of memory' in func 'cuda_neoscrypt::init' line 1258

**Comment by dropky** [comment] 2018-01-11 10:19
Increasing virtual memory size should solve the problem. #104

**Comment by dropky** [comment] 2018-01-15 14:17
So I can finally reproduce this issue. When running standalone excavator everything works fine, but if there is NHM running on the system (doesn't have to be mining, it's enough that it's opened), then 'out of memory' crash occurs on the primary GPU. To avoid such issues, I suggest you to disable NeoScrypt on your primary card (only primary GPU is problematic, at least in my case) until this bug is fixed by the NHM team. Of course, the crash can still happen when using a standalone Excavator, since third party applications that are GPU consuming can crash the primary card as well, in such case just do the same - don't run neoscrypt on your primary card. 

If this issue persists in the future, we'll work on a different implementation of the NeoScrypt (that won't need as much memory as current one). 

I'm closing this (will reopen if needed), thank you all for your feedback! Keep on mining :) 

Btw, we released new version of excavator today - https://github.com/nicehash/excavator/releases/tag/v1.3.9a

**Closed by dropky** 2018-01-15 14:17 UTC
Labels: bug

**Comment by MossP** [comment] 2018-03-02 20:43
@dropky I have started seeing this error on v2.0.1.11 even though my primary card is my separate onboard graphics card. Has something changed in the latest build?

**Comment by MossP** [comment] 2018-03-02 20:50
@dropky Apologies, it appears that my primary card has switched to one of my mining cards. I'll apply the fixes suggested and try again. Thanks for the info.
