### ISSUE TITLE
Clear console command, API?

### ISSUE THREAD

**Issue by mayhem7** [nicehash/excavator#230] opened 2018-03-29 21:57 UTC
I've checking the API but can't find any command to "clear" the console, W10 always crashes after 48h running excavator, it seems an issue with the looooooong console log, i've been testing this week, if i stop/start excavator every 24h there's no problem, but if it reaches 36-48h windows dies :(

**Comment by dropky** [comment] 2018-03-30 06:22
Clear command isn't supported in the API. We'll take a look at the issue you're describing. Which version of NVIDIA driver do you have? Which Windows build do you use?

**Comment by mayhem7** [comment] 2018-03-30 09:11
Thanks for fast reply:
Windows 10 Pro
Windows build: 1709 (was using a previous one but tried updating everything, didn't fix the issue)
Using driver version: 391.35
Also tried with previous: 391.24

**Comment by mayhem7** [comment] 2018-03-31 18:56
Tested again, 24h = blue screen
Currently 48h with ccminer without issues, so it must be excavator dunno why... i'll make a script to auto-restart system every 12 hours to avoid the blue screen.

**Comment by dropky** [comment] 2018-04-03 12:34
I've been testing excavator over the weekend and unfortunately I couldn't reproduce the issue. Will try some more.

**Comment by mayhem7** [comment] 2018-04-03 15:52
Tried yesterday again, 11 hours and blue screen, only happens with excavator, dunno why :( i've increased virtual memory to 36GB because i really think is the console, will tell you on the next crash ^^'

**Comment by mayhem7** [comment] 2018-04-04 23:15
Testings going good, increasing virtual memory when using excavator works:
16GB virtual memory = BSOD in 12 hours
32GB virtual memory = BSOD  in 24+ hours
Testing wih 64GB virtual memory

**Comment by dropky** [comment] 2018-04-05 06:15
That explains why I couldn't reproduce the issue. If increasing the virtual memory helps then I suggest you to stick with it until the issue is resolved otherwise.

**Comment by nicehashdev** [comment] 2021-01-07 07:23
Run excavator with -d 2 and rather keep displaying details in files (-f 1 or -f 0) to avoid this issue. Closing.

**Closed by nicehashdev** 2021-01-07 07:23 UTC
Labels: enhancement
