### ISSUE TITLE
Maybe error in API over TCP

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#214] opened 2018-03-11 20:12 UTC
For example:
Request {"id":1,"method":"algorithm.list","params":[]} 
Answer {"version":"1.4.4a_nvidia","build_platform":"Windows","build_time":"2018-02-16 13:11:25","build_number":4645,"uptime":9706703,"cpu_load":70.40237425816905,"cpu_usage":1.5590448448149213,"ram_load":59.0,"ram_usage":691.6328125,"id":1,"error":null}

- The TCP buffer is cleared before the request (ie, it is not the old data).
- The error occurs when accessing one instance of the excavator from several threads or applications (i.e., several TCP sessions).
- The error is not reproduced when using the HTTP connection.
Such a feeling that the Excavator forgets who asked him, and gives the data in the any session.

**Comment by dropky** [comment] 2018-03-12 08:23
I'm gonna take a look, thanks for the report.

**Comment by nicehashdev** [comment] 2021-01-07 07:26
We were not able to reproduce this. Perhaps you did not read data from TCP and you read the old message? Closing.

**Closed by nicehashdev** 2021-01-07 07:26 UTC
