### ISSUE TITLE
NeoScrypt

### ISSUE THREAD

**Issue by MichaelMiner** [nicehash/excavator#133] opened 2018-01-19 19:17 UTC
Excavator 1.4.0a NeoScrypt not work - out of memory

**Comment by dropky** [comment] 2018-01-19 19:29
On which GPU? Do you have enough virtual memory?

**Comment by MichaelMiner** [comment] 2018-01-19 19:32
8 x NVidia Evga GeForce 1080 Ti Black Edition
Vitual memory 23 Gb


>Пятница, 19 января 2018, 22:29 +03:00 от dropky <notifications@github.com>:
>
>On which GPU? Do you have enough virtual memory?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Михаил Филимонов

**Comment by MichaelMiner** [comment] 2018-01-19 19:33
Sorry 32 Gb


>Пятница, 19 января 2018, 22:29 +03:00 от dropky <notifications@github.com>:
>
>On which GPU? Do you have enough virtual memory?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Михаил Филимонов

**Comment by dropky** [comment] 2018-01-19 19:48
That's not enough, you should set your virtual memory to at least amount of total GPU memory of all cards combined together, in your case.. 8 x 11 = 88 gb.

**Comment by MichaelMiner** [comment] 2018-01-19 19:54
Other algorithms work without problems


>Пятница, 19 января 2018, 22:48 +03:00 от dropky <notifications@github.com>:
>
>That's not enough, you should set your virtual memory to at least amount of total GPU memory of all cards combined together, in your case.. 8 x 11 = 88 gb.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Михаил Филимонов

**Comment by dropky** [comment] 2018-01-19 19:56
The thing is that neoscrypt needs more memory than other algorithms.

**Comment by MichaelMiner** [comment] 2018-01-19 20:12
Almost all miners have SSD 64-120 GB


>Пятница, 19 января 2018, 22:56 +03:00 от dropky <notifications@github.com>:
>
>The thing is that neoscrypt needs more memory than other algorithms.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Михаил Филимонов

**Comment by aKra-NL** [comment] 2018-01-19 23:36
Excavator 1.4.0a on NeoScrypt with 2 x NVidia 1080 Ti and a pagefile of 64GB.

Out of memory issue... Hmm?

**Comment by Incarnation** [comment] 2018-01-20 00:13
Excavator 1.4.0a on NeoScrypt , 13 GTX 1060 3GB , virtual memory 160GB+

Mine Keep crashing every 10 minutes or so

**Comment by zeittresor** [comment] 2018-01-20 19:22
Same issue here GTX 1060 GB 3GB "Out of Memory Error"; System Ram 24GB; Core i5; 20 TB SSHDs

**Comment by zeittresor** [comment] 2018-01-20 20:15
I think i've found a solution for the Problem.. the Problem is not Excavator v1.4.0a you should install https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal (NetWork Edition), after the Installation NeoScript is working fine (for me) :-)

**Comment by Incarnation** [comment] 2018-01-21 04:00
@zeittresor it seem that you are rolling back the NVIDIA driver to 388.19 if you install that,  my current driver is 388.71 and it seems more stable with 388.71 (the newest driver is 390.65)

**Comment by EvgeniyKorepov** [comment] 2018-01-21 08:13
Yesterday I updated the drivers to 390 and the excavator began to work much more stable - 8 and 14 hours, it's very good!
<img width="787" alt="nhmpro001" src="https://user-images.githubusercontent.com/35364901/35192070-8bf42e46-fe9b-11e7-85cf-50b284ca8efb.PNG">

Rigs node07 and node09 - drivers are updated. Prior to updating, uptime did not exceed two hours.

**Comment by MichaelMiner** [comment] 2018-01-21 14:51
>>update: I think i've found a solution for the Problem.. 
Excavator use cudart64_80.dll
>>Yesterday I updated the drivers to 390 and the excavator began to work much more stable - 8 and 14 hours, it's very good!
I'm update driver to 390.65 and set virtual memory 48 Gb - Out of memory

**Comment by zeittresor** [comment] 2018-01-22 21:38
@EvgeniyKorepov Nicehash Miner "PRO" ?!

**Comment by dropky** [comment] 2018-01-23 07:28
Hmm... Version 1.4.0 is using half the amount of memory than the previous versions, I was pretty sure that would solve the issue. I'm gonna look into the 'cuda out of memory' problem some more. Also I'm gonna prepare a different default parameters (with as low performance loss as possible) that will use even less memory and you can try to run neoscrypt with them then.  

I have a question for all of you, are you using standalone excavator or NiceHash Miner? If you're using NHM try to disable neoscrypt on the primary card.

**Comment by EvgeniyKorepov** [comment] 2018-01-23 10:07
@zeittresor This is a system for managing an unlimited number of instances of the Excavator running locally or remotely.

The calculation of profits is made taking into account the cost of electricity. Including different cost of electricity during the day.
Individual overclocking for each algorithm.
Fine-tuning the parameters of algorithms.
Ability to change parameters of the algorithm overclocking during operation.
Fast, about a second, switch between algorithms.
Failover - switching to other locations when the stratum server fails.

Miner will be available in the coming days at https://github.com/EvgeniyKorepov/NiceHashMinerPro

**Comment by dropky** [comment] 2018-01-23 13:52
@EvgeniyKorepov To avoid potential trademark infringement, please change the name and remove the NH logo from your miner. For example, you can change the name to something like Pro Miner for Nicehash or Miner Pro for Nicehash.

**Comment by EvgeniyKorepov** [comment] 2018-01-23 14:58
@dropky You're right. I'll make changes.

**Comment by zeittresor** [comment] 2018-01-26 13:33
I have new problem with excavator since update to v1.4.1a, NeoScript is going slower over time, @start it was approx 639 kH/s @ Asus Geforce 1060 GTX 3GB. It's working but getting slower over time. After approx 5h worktime it's @ 603 kH/s. After restart it's again @ 639 kH/s :-/

**Comment by dropky** [comment] 2018-01-26 14:01
@zeittresor For the version 1.4.1a, we uploaded the build compiled with CUDA 9.1 as well, if you use this one, do you still encounter the same problem? You can download it from here: [excavator_v1.4.1a_NVIDIA_Win64_CUDA_9.1.zip](https://github.com/nicehash/excavator/releases/tag/v1.4.1a )

Are you running NHM or standalone excavator? If you're running NHM could you add -f 0 to ExcavatorStartupParameters and send me the excavator log files?

**Comment by rwaters71** [comment] 2018-01-27 14:40
Comparing a single Asus GTX1060 6GB (stock clocks), my max hashrate with escavator 1.4.1a is ~680 KH/s. Same card/rig with hsrminer gives me average rate of 815 KH/s.

Any ideas?

Because of the huge difference, I am stuck without auto-switching if I have to use a 3d party miner with NHM2 it seems.

**Comment by dropky** [comment] 2018-01-29 12:32
@rwaters71 Try using CUDA 9.1 build, you should get better results.

**Comment by dropky** [comment] 2018-01-30 06:43
> I have new problem with excavator since update to v1.4.1a, NeoScript is going slower over time, @ start it was approx 639 kH/s @ Asus Geforce 1060 GTX 3GB. It's working but getting slower over time. After approx 5h worktime it's @ 603 kH/s. After restart it's again @ 639 kH/s :-/

@zeittresor Any update on this? If you use CUDA 9.1 build does the speed still fall over time?

**Comment by rwaters71** [comment] 2018-01-30 13:38
CUDA 9.1 seems to work a bit better for my GTX 1060 6GB than CUDA 8.0.

**Comment by dropky** [comment] 2018-01-30 14:09
@rwaters71 Great, thanks!

**Comment by dropky** [comment] 2018-01-30 16:05
We released a new version today - https://github.com/nicehash/excavator/releases/tag/v1.4.2a. Drivers 387.xx or more recent are required. New version includes speed improvements for neoscrypt and multiple bug fixes (including the one causing low hashrate on neoscrypt when switching from equihash).

**Comment by Creamel** [comment] 2018-01-30 19:42
I have:
2 x MSI Geforce 1070 GTX 8GB
2 x MSI Geforce 1070 Ti GTX 8GB

if i run neoscrypt on ccminer (ccminer-x64-75.exe) or run old nhm 1.7.5.13 - total hashrate about 4.2-4.3 MH

if i run nhm2 with excavator 1.3.4-1.4.1 - total hashrate about 3.5-3.6 MH
if i run nhm2 with excavator 1.4.2 - total hashrate about 3.85 MH

why hashrate fall on excavator?

**Comment by rwaters71** [comment] 2018-01-30 21:34
Neoscrypt hashrate with 1.4.2a seems much better than 1.4.1 (both CUDA 8.0 and 9.1) for me, very close to other great neoscrypt miners (just ran a very quick hashrate comparison with hsrminer and the original djm34 ccminer, whatever that's worth).

Thanks for your work, it's appreciated!

**Comment by Creamel** [comment] 2018-01-30 22:05
i run hsrminer and got the result - 5.3 MH. it's fantastic!
but, i like nhm and i want work with it.

what should i do?

**Comment by rwaters71** [comment] 2018-01-30 22:17
Not sure how accurate self-reported miner speeds are, and hsrminer is closed source, with 1% dev fee.. but yeah, it's self-reportedly somewhat faster.

**Comment by Creamel** [comment] 2018-01-31 08:42
wow!!! i update nhm2 to 2.0.1.10 and got the result 5.2MH on neoscrypt algo. it's amazing :)

**Comment by dropky** [comment] 2018-02-15 11:47
I'm closing this, thank you all for your feedback!

**Closed by dropky** 2018-02-15 11:47 UTC
