### ISSUE TITLE
Excavator is very sensitive to overclock - NeoScrypt

### ISSUE THREAD

**Issue by borzaka** [nicehash/excavator#164] opened 2018-02-01 12:51 UTC
Every other miner (and even Excavator on another algorithm) works for a long time with my overclock settings, but not Excavator NeoScrypt.

After 15-20 minutes:
`CUDA error 'unspecified launch failure' in func 'cuda_neoscrypt::run'`

![image](https://user-images.githubusercontent.com/1230402/35671888-fbf7f5d4-073c-11e8-8d12-ace82215f26d.png)

Latest Version 1.4.2 alpha NVIDIA release.
Overclock: 100% power, +200 MHz core, +600 MHz memory (3 1070 Ti) - If I lower my overclocks to +100 MHz/+500Mhz it works, but other algorithms are hashing slower.
Driver: 388.71
OS: Windows 10 64 bit, 8GB RAM, 60GB virtual memory

Related: #160 (3 1080 Ti)

Any recommended overclock settings for Excavator? For 1070 Ti and 1080 Ti.

**Comment by niknewb** [comment] 2018-02-01 13:16
Have you tried +190-200 core and +400-450 Mhz vram? I'm running with these setting on my 1070 Ti rigs, idk about 1080Tis since I use NHML on them

**Comment by dropky** [comment] 2018-02-02 17:02
@borzaka Try the newest version of excavator, it should be more stable. 

As far as the recommended settings go I can tell you for 1080 Ti, I have them set at 65% power, -300 memory and +175 core.

Also, check this post - https://www.reddit.com/r/NiceHash/comments/6wc655/1080ti_settinga/?st=J6Z4ODIM&sh=0fdb89db

**Comment by borzaka** [comment] 2018-02-02 19:21
With the new Excavator (Version 1.4.3 alpha NVIDIA):
- 3 1080 Ti (100%, +100MHz, +600MHz)
- 3 1070 Ti (100%, +200Mhz, +650MHz)
- stable with other miners and algorithms

After ~10 minutes:
![image](https://user-images.githubusercontent.com/1230402/35749440-d114ce94-0851-11e8-9841-65ac76b3bcfc.png)

Lowering the 3 1070 Ti's memory clock to +600 MHz: it doesn't crashed for 45 minutes and counting... still running tests. I'll report back if I have any news.
**So, you are right, it's more stable ;)** Thank you!

Also thank you for your 1080 Ti settings, but it's too weak for me. I'am switching algorithms, and I need the GPU and memory power :) Are you running only GPU dependent algorithms? Or I'am wrong; no algorithms can profit from that much memory overclock?

_Note: Electricity cost doesn't affect me, so my settings are not optimized electricity wise!_

**Comment by dropky** [comment] 2018-02-03 13:01
Great! Since the issue is solved I'm closing it. 

Regarding the OC settings for 1080 Ti. I find them the most efficient per watt (since cost of electricity does affect me ;) ). Also, they turned out to be stable - I had some problems with my PSU when setting to higher power limit.

**Closed by dropky** 2018-02-03 13:01 UTC
