### ISSUE TITLE
nhmp | read: End of file (2) errors

### ISSUE THREAD

**Issue by borzaka** [nicehash/excavator#265] opened 2018-06-24 11:30 UTC
Basic information:
- NiceHash Miner 2.0.2.4 - Beta
- Excavator v1.5.5a
- I enabled only the 1070 Tis in NHM2, the 1080 Tis was mining with a different program
- probably one of my card crashed sometime, what caused issues (or Excavator make it crash, see below)
- Logs attached at the end.

Problems I see:
- Excavator restarted sometime by own.
- lot of `End of file (2)` warning at the beginning
- Excavator subscribed to different algorithms at the same time.
- Excavator was receiving jobs from different algorithms.
- Excavator displaying hashing speed for unsubscribed algorithms.
- Excavator tried to mine different algorithms at the same time?
- Excavator tried to mine with the disabled cards as well, that caused a crash?

Thoughts:
- Excavator/NHM2 forgets the disabled cards?
- NHM2 not saving enabled/disabled cards until a proper closing?
- When a card is crashing, Excavator/NHM2 starts acting weird, even it's a non enabled card in NHM2.

```
=========================== www.nicehash.com =========================
           Excavator v1.5.5a_nvidia GPU Miner for NiceHash.
           Copyright (C) 2018 NiceHash. All rights reserved.
=========================== www.nicehash.com =========================

Build time: 2018-06-14 13:19:49
Build number: 5945
Provided startup commandline:
        C:\Users\Attila\AppData\Roaming\nhm2\bin\excavator_server\excavator.exe  -wp 38080 -p 5101 -na

[07:58:11][0x00001cbc][info] Log started
[07:58:31][0x00001cbc][info] core | Found CUDA device: GeForce GTX 1080 Ti
[07:58:46][0x00001cbc][info] core | Found CUDA device: GeForce GTX 1080 Ti
[07:58:46][0x00001cbc][info] core | Found CUDA device: GeForce GTX 1080 Ti
[07:58:46][0x00001cbc][info] core | Found CUDA device: GeForce GTX 1070 Ti
[07:58:46][0x00001cbc][info] core | Found CUDA device: GeForce GTX 1070 Ti
[07:58:46][0x00001cbc][info] core | Found CUDA device: GeForce GTX 1070 Ti
[07:58:46][0x00001cbc][info] api | Listening on 127.0.0.1:5101
[07:58:46][0x00001cbc][info] http | Listening on 127.0.0.1:38080
[07:58:46][0x00001cbc][info] core | Initialized!
[07:58:48][0x00001cbc][info] Connected to nhmp.eu.nicehash.com:3200
[07:58:48][0x000000c4][info] nhmp | Subscribed
[07:58:52][0x00001cbc][info] nhmp | Disconnected
[07:58:52][0x00001cbc][warning] nhmp | read: End of file (2)
[07:59:02][0x000000c4][info] Connected to nhmp.eu.nicehash.com:3200
[07:59:02][0x000000c4][info] nhmp | Subscribed
[07:59:07][0x000000c4][info] nhmp | Disconnected
[07:59:07][0x000000c4][warning] nhmp | read: End of file (2)
[07:59:17][0x000000c4][info] Connected to nhmp.eu.nicehash.com:3200
[07:59:17][0x000000c4][info] nhmp | Subscribed
[07:59:21][0x000000c4][info] nhmp | Disconnected
[07:59:21][0x000000c4][warning] nhmp | read: End of file (2)
[07:59:31][0x000000c4][info] Connected to nhmp.eu.nicehash.com:3200
[07:59:31][0x000000c4][info] nhmp | Subscribed
[07:59:36][0x000000c4][info] nhmp | Disconnected
[07:59:36][0x000000c4][warning] nhmp | read: End of file (2)
[07:59:46][0x000000c4][info] Connected to nhmp.eu.nicehash.com:3200
[07:59:46][0x000000c4][info] nhmp | Subscribed
[07:59:50][0x00001cbc][info] nhmp | Disconnected
[07:59:50][0x00001cbc][warning] nhmp | read: End of file (2)
[08:00:00][0x00001cbc][info] Connected to nhmp.eu.nicehash.com:3200
[08:00:00][0x00001cbc][info] nhmp | Subscribed
[08:00:05][0x00001cbc][info] nhmp | Disconnected
[08:00:05][0x00001cbc][warning] nhmp | read: End of file (2)
[08:00:15][0x000000c4][info] Connected to nhmp.eu.nicehash.com:3200
[08:00:15][0x000000c4][info] nhmp | Subscribed
[08:00:20][0x00001cbc][info] nhmp | Disconnected
[08:00:20][0x00001cbc][warning] nhmp | read: End of file (2)
[08:00:30][0x00001cbc][info] Connected to nhmp.eu.nicehash.com:3200
[08:00:30][0x00001cbc][info] nhmp | Subscribed
[08:00:34][0x00001cbc][info] nhmp | Disconnected
[08:00:34][0x00001cbc][warning] nhmp | read: End of file (2)
[08:00:44][0x00001cbc][info] Connected to nhmp.eu.nicehash.com:3200
[08:00:44][0x00001cbc][info] nhmp | Subscribed
[08:00:49][0x000000c4][info] nhmp | Disconnected
[08:00:49][0x000000c4][warning] nhmp | read: End of file (2)
[08:00:59][0x00001cbc][info] Connected to nhmp.eu.nicehash.com:3200
[08:00:59][0x00001cbc][info] nhmp | Subscribed
[08:01:03][0x00001cbc][info] nhmp | Disconnected
[08:01:03][0x00001cbc][warning] nhmp | read: End of file (2)
[08:01:13][0x00001cbc][info] Connected to nhmp.eu.nicehash.com:3200
[08:01:13][0x00001cbc][info] nhmp | Subscribed
[08:01:18][0x000000c4][info] nhmp | Disconnected
[08:01:18][0x000000c4][warning] nhmp | read: End of file (2)
[08:01:28][0x000000c4][info] Connected to nhmp.eu.nicehash.com:3200
[08:01:28][0x000000c4][info] nhmp | Subscribed
[08:01:32][0x00001cbc][info] nhmp | Disconnected
[08:01:32][0x00001cbc][warning] nhmp | read: End of file (2)
[08:01:35][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:35][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:38][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:38][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:38][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:38][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:39][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:39][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:39][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:39][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:39][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:39][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:39][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:39][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:39][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:39][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:42][0x000000c4][info] Connected to nhmp.eu.nicehash.com:3200
[08:01:42][0x000000c4][info] nhmp | Subscribed
[08:01:43][0x000000c4][info] nhmp | lyra2rev2 | add success
[08:01:43][0x000000c4][info] net | lyra2rev2 | New job '0000005c1e715009', diff=0.5
[08:01:44][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:44][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:44][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:46][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:46][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:47][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:47][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:47][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:47][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:47][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:01:47][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:01][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:09][0x000000c4][info] net | lyra2rev2 | New job '0000005c1e718802', diff=0.5
[08:02:16][0x000000c4][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:16][0x000000c4][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:16][0x000000c4][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:16][0x000000c4][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:16][0x000000c4][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:16][0x000000c4][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:16][0x000000c4][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:17][0x000000c4][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:17][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:17][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:17][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:17][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:17][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:17][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:17][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:17][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:17][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:22][0x00001cbc][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:25][0x000000c4][info] core | Algorithm 'neoscrypt' speed: 0.000000 H/s
[08:02:25][0x000000c4][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:25][0x000000c4][info] core | Algorithm 'lyra2z' speed: 0.000000 H/s
[08:02:25][0x000000c4][info] core | Algorithm 'neoscrypt' speed: 0.000000 H/s
[08:02:25][0x000000c4][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:25][0x000000c4][info] core | Algorithm 'lyra2z' speed: 0.000000 H/s
[08:02:25][0x00001cbc][info] nhmp | lyra2z | add success
[08:02:25][0x000000c4][info] core | Algorithm 'neoscrypt' speed: 0.000000 H/s
[08:02:25][0x000000c4][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:25][0x000000c4][info] core | Algorithm 'lyra2z' speed: 0.000000 H/s
[08:02:25][0x00001cbc][info] net | lyra2z | New job '0000009e2bb5c87d', diff=0.0078125
[08:02:25][0x00001cbc][info] nhmp | neoscrypt | add success
[08:02:25][0x00001cbc][info] net | neoscrypt | New job '00000045f89609a0', diff=0.125
[08:02:25][0x000000c4][info] core | Algorithm 'neoscrypt' speed: 0.000000 H/s
[08:02:25][0x000000c4][info] core | Algorithm 'lyra2rev2' speed: 0.000000 H/s
[08:02:25][0x000000c4][info] core | Algorithm 'lyra2z' speed: 0.000000 H/s
```

Logs:
[log.txt](https://github.com/nicehash/excavator/files/2130701/log.txt)

**Comment by danmogo** [comment] 2018-06-25 13:20
Same exact problem.

**Comment by dropky** [comment] 2018-06-27 07:44
Thanks for the report, we are working on a solution. This should be fixed with the upcoming NiceHash Miner release. Currently the best way to avoid this is to prevent the excavator from crashing.

**Comment by S74nk0** [comment] 2018-06-27 11:10
This is nhm2 *bug* we should have this fixed in the next upcoming release. Please keep this issue open and close it if the next upcoming release solves the problem.

**Comment by khusnullin** [comment] 2018-06-28 13:08
This bug is also present on the Linux version of the excavator_1.5.5a (cryptonightv7 algorithm).

**Comment by dropky** [comment] 2018-06-28 13:16
@khusnullin Does this happen after a share hasn't been found for quite some time (due too the high difficulty on cryptonightv7)? If that's the case, then it's not a bug. Stratum server will drop inactive connection after share hasn't been sent for x minutes, excavator will reconnect if everything is alright and continue mining.

**Comment by khusnullin** [comment] 2018-06-28 13:56
@dropky 
This happens when the miner is initialized. After ~5 minutes of downtime, usually the mining starts working.
In Windows excavator starts working immediately (with the same configuration file).
json:
`[
    {"time":0,"commands":[
		{"id":1,"method":"subscribe","params":["nhmp.jp.nicehash.com:3200","hidden_wallet"]}
	]},
    {"time":2,"commands":[
		{"id":1,"method":"algorithm.add","params":["cryptonightV7","hidden_wallet"]}
    ]},
    {"time":3,"commands":[
		{"id":1,"method":"worker.add","params":["cryptonightV7","0"]},
		{"id":1,"method":"worker.add","params":["cryptonightV7","1"]},
		{"id":1,"method":"worker.add","params":["cryptonightV7","2"]},
		{"id":1,"method":"worker.add","params":["cryptonightV7","3"]},
		{"id":1,"method":"worker.add","params":["cryptonightV7","4"]},
		{"id":1,"method":"worker.add","params":["cryptonightV7","5"]}
    ]},
    {"time":10,"loop":10,"commands":[
		{"id":1,"method":"worker.print.speed","params":["0"]},
		{"id":1,"method":"algorithm.print.speeds","params":["0"]}
    ]}
]`

**Comment by dropky** [comment] 2018-06-28 14:02
@khusnullin Can you run excavator with -f 0 parameter and post here the log file? What version of driver are you using?

**Comment by khusnullin** [comment] 2018-06-28 15:06
@dropky 
I looked at the logs... Sorry guys.
Instead of json, the excavator reads garbage.
The problem with the file system, not with the miner.
Thanks for the support.

**Comment by xgnom666x** [comment] 2018-07-21 09:42
HiveOs,nvidia 390.67 and 396.45,excavator 1.5.8
[log.txt](https://github.com/nicehash/excavator/files/2216048/log.txt)

**Comment by RavenouseAnimal** [comment] 2018-08-30 10:32
@S74nk0 
hi
when will solve the bug with NHM2?

**Comment by baskice** [comment] 2018-11-18 01:15
Got same problem today.

**Comment by nicehashdev** [comment] 2021-01-07 07:14
This happens when connection with server is lost. Not a bug. Closing.

**Closed by nicehashdev** 2021-01-07 07:14 UTC
