### ISSUE TITLE
Lyra2REv2 low hashrate on pools

### ISSUE THREAD

**Issue by Atexor** [nicehash/excavator#223] opened 2018-03-25 01:07 UTC
Hi
Few months ago I was trying to mine MonaCoin on Mining Pool Hub, but I noticed that pool detects ~30mh/s although the miner was showing ~50mh/s.

Few hours ago I wanted to check it again because someone had told me that it gives better results than ccminer for Lyra2REv2. So I downloaded latest version to mine Straks coin on datapaw pool and noticed the same issue: https://i.imgur.com/4HwTiP7.png

OS: Windows 10 PRO x64
GPU: ASUS ROG STRIX-GTX1080-O8G

Could you take a look on it? I'm using standard config with one worker:
```
[
	{"time":0,"commands":[
		{"id":1,"method":"algorithm.add","params":["lyra2rev2","pool.datapaw.net:4533","my_wallet"]}
	]},
	{"time":3,"commands":[
		{"id":1,"method":"worker.add","params":["0","0"]}
	]},
	{"time":10,"loop":20,"commands":[
		{"id":1,"method":"worker.print.speed","params":["0"]},
		{"id":1,"method":"algorithm.print.speeds","params":["0"]}
	]}
]
```

**Comment by swamprunner7** [comment] 2018-03-29 10:47
Same, using ccminer nanashi for now.

**Comment by Atexor** [comment] 2018-03-29 11:47
Which graphics card do you have? The same as me? I'm using ccminer nanashi too.

Maybe it's issue only with our GPUs.

**Comment by swamprunner7** [comment] 2018-03-29 11:49
1080ti, real 70Mh on nanashi, strange 74Mh on excavator in console but only ~half in the pool.

**Comment by dropky** [comment] 2018-03-29 11:51
Which version of excavator are you using?

**Comment by swamprunner7** [comment] 2018-03-29 11:52
v1.4.4a

**Comment by Atexor** [comment] 2018-03-29 11:55
1.4.4a too but noticed that issue on 1.3.8a version few months ago.

**Comment by swamprunner7** [comment] 2018-03-29 11:57
Seems like when nicehash miner 2 using it, console showing same results like nanashi ~70

**Comment by dropky** [comment] 2018-03-29 11:57
This problem happens only on one pool? Which one? For which coin?

**Comment by swamprunner7** [comment] 2018-03-29 12:02
Looked again, actually no, nicehashminer2 doing right now 74Mh on Lyra2v2, so something wrong with excavator for other pools, because pool instantly showing correct data from nanashi.

**Comment by swamprunner7** [comment] 2018-03-29 12:08
Tried xvg-lyra.suprnova.cc

**Comment by Atexor** [comment] 2018-03-29 12:36
1.3.8a few months ago - Monacoin on https://miningpoolhub.com/
1.4.4a now - Straks on https://datapaw.net/

Both coins using lyra2rev2 algo. Both pools detects ~50-60% of the hashrate in miner.

**Comment by dropky** [comment] 2018-03-29 12:53
I can't reproduce the same issue when using NiceHash stratum and since we recently dropped the support for other pools there isn't much I can do at the moment.

**Comment by Atexor** [comment] 2018-03-29 13:27
I don't use stratum in excavator because I can't connect with it to any pool, even to nicehash
	{"id":1,"method":"algorithm.add","params":["lyra2rev2","stratum+tcp://lyra2rev2.eu.nicehash.com:3347","address.worker"]}

I don't know whether excavator supports it, hovewer I can check it with supported pools/connecting methods (with/without stratum).
Just let me know how to configure it if you want.

**Comment by borzaka** [comment] 2018-03-29 23:21
I'am experiencing the the same issue; lyra2rev2 pool side hashrate is almost half as shown in the miner.

I have a following setup:
- 3x 1080 Ti
- 3x 1070 Ti
- Excavator Version 1.4.4 alpha NVIDIA
- [A Hash Pool](https://ahashpool.com/) lyra2v2 algo
- 395 MH/s lyra2rev2 performance with overclocks:

![image](https://user-images.githubusercontent.com/1230402/38116407-34f3da0c-33b0-11e8-990f-f7482b17dcf1.png)

But on the pool side, my hashrate is fluctuating, and the average hashrate is almost half compared with the miner:
![image](https://user-images.githubusercontent.com/1230402/38116424-41d7546a-33b0-11e8-9af4-a96da465adf6.png)
And my earnings after 24 hour is almost half as well: whattomine 24 hour estimate. It was not even near.

What's the problem? When I was mining NeoScrypt with Excavator to the same pool, the graph was accurate, as my earnings.

This is my config: [AHashPool_Lyra2RE2_config.txt](https://github.com/nicehash/excavator/files/1862202/AHashPool_Lyra2RE2_config.txt)

I know, that the new versions of Excavator doesn't support other pools, but this issue maybe still present.

**Comment by dropky** [comment] 2018-03-30 06:30
@Atexor 

> I don't use stratum in excavator because I can't connect with it to any pool, even to nicehash
> {"id":1,"method":"algorithm.add","params":["lyra2rev2","stratum+tcp://lyra2rev2.eu.nicehash.com:3347","address.worker"]}

Stratum URL has to be without stratum+tcp:// prefix. You should call algorithm.add method like this:
`{"id":1,"method":"algorithm.add","params":["lyra2rev2","lyra2rev2.eu.nicehash.com:3347","address.worker"]}
`

Let me know if you have any issues with the pool speed.

**Comment by dropky** [comment] 2018-03-30 06:31
@borzaka Try using one worker per device.

**Comment by swamprunner7** [comment] 2018-03-30 06:51
I'm using gui by cTnko, and just pool address without protocol and get same result. Just tried 6 jobs for each card, speeds not correct too, and  because job only for one card each time, seems like it's taking only low difficulty.

**Comment by Atexor** [comment] 2018-03-30 17:45
@dropky I can't find any charts for my hashrate  on nicehash, but it shows my 55-70 MH/s (I've ~52)  there: https://www.nicehash.com/miner/my_address

So it looks that excavator works only on nicehash but on any others pools it's sadly broken. I realise that you said that others pools are unsupported hovewer it's really strange.

**Comment by swamprunner7** [comment] 2018-03-30 17:47
neoscrypt working ok anywhere, just tried

**Comment by Atexor** [comment] 2018-03-30 17:55
Hovewer there are other algos too. There is a bug somewhere with lyra2rev2 so I reported it.

**Comment by swamprunner7** [comment] 2018-03-30 17:57
Until it will be fixed, i trying other algos with neoscrypt :)

**Comment by borzaka** [comment] 2018-03-30 23:15
@dropky I have tried with one worker per device. The results are the same; pool side hashrate is almost half.

Excavator reports that I have 394 MH/s:
![image](https://user-images.githubusercontent.com/1230402/38156644-d9f55452-347f-11e8-8724-72888e0a8ee0.png)

[A Hash Pool](https://www.ahashpool.com/) sees only half at average, and it's very fluctuating:
![image](https://user-images.githubusercontent.com/1230402/38156678-1c67f16e-3480-11e8-9183-fefcf8c761ef.png)
~12 hour testing

This is my one worker per device config: [AHashPool_Lyra2RE2_1worker_config.txt](https://github.com/nicehash/excavator/files/1864970/AHashPool_Lyra2RE2_1worker_config.txt)

**Comment by swamprunner7** [comment] 2018-03-31 07:36
I tried neoscrypt again for hour, seems like same stuff. On start doing great speed and pool showing it but after few minutes 5% rejected shares and speed drop.

**Comment by borzaka** [comment] 2018-03-31 10:14
I have no problem with NeoScrypt on A Hash Pool, the pool side hashrate is same as shown in the miner as should be.

**Comment by apiontek** [comment] 2018-03-31 14:34
I have experienced this problem as well. Tested and got the same results on both ahashpool and miningpoolhub.

I also have consistently about 15% lower results from excavator with Neoscrypt, as compared with KlausT ccminer.

**Comment by dropky** [comment] 2018-04-03 12:39
> So it looks that excavator works only on nicehash but on any others pools it's sadly broken. I realise that you said that others pools are unsupported hovewer it's really strange.

I'm closing this issue since the problem can't be reproduced on NiceHash stratums (and support for other pools was dropped).

**Closed by dropky** 2018-04-03 12:39 UTC
