### ISSUE TITLE
Why does my Titan V have Exponentially higher Hash Rates with Version 2.0.5

### ISSUE THREAD

**Issue by Sephiroth4269** [nicehash/excavator#191] opened 2018-02-18 04:14 UTC
![proof](https://user-images.githubusercontent.com/36573672/36348173-e32e51e4-1437-11e8-97ac-bb202d8a16b0.png)
This is a real screen shot from my computer where I was trying to mine Cryptonight. I don't necessarily care that it didn't work, I want to know why it didn't work, and where on my PC are these algorithms located so I can mess around with the parameters. Secondly I am positive it has to do with CUDA compatibility that 2.0.5 didn't have the ability to talk with 9.1 and somehow those cores weren't implemented in the 2.0.10 update. 

I have look high and low trying to find the raw algorithm on my computer, read all of the readme files and have no idea where to look. No other forums are discussing it either, and I am fully aware that it is a level of programming far beyond Amateur. That being said I would still like to try, I have all of the recommended software to edit the code, but I can't find it, and I don't know what I am looking for. 

Please help!

**Comment by dropky** [comment] 2018-02-18 10:47
We added support for Titan V in [1.4.3 version](https://github.com/nicehash/excavator/releases/tag/v1.4.3a). You should try to run that one or more recent. The version of excavator that you're running wasn't built for 7.0 architecture (and it can't work on Titan V because of that). 

I'm not quite sure what you mean by "find the raw algorithm on my computer" but just to be clear excavator is a closed source software, so you can't find and edit the code.

**Comment by Sephiroth4269** [comment] 2018-02-18 17:54
Well that makes more sense. That being said, those numbers are real numbers, the Titan V is capable of pushing those kinds of numbers from the 2.0.5 version of the Nice Hash Miner. I would recommend maintaining the same algorithm structure of the older version, and making the updates to handle CUDA 9.1. Of course if that is what you guys did, then I'm not sure what happened, it seems like the algorithm isn't utilizing nearly enough of the hardware.

**Comment by dropky** [comment] 2018-02-21 13:58
I performed more tests on Titan V and you're right. 

```
Excavator version: 1.3.8a_nvidia
TITAN V: speed = 1.7619 MH/s, power usage = 33.975 W

Excavator version: 1.4.4a_nvidia
TITAN V: speed = 1.1913 kH/s, power usage = 69.982 W
```

The only difference between these two versions is that the first one wasn't compiled for Titan V and the second one was (source code is the same). Version 1.3.8 includes ptx and since it doesn't include the architecture for Titan V, compiling is done by the driver (just-in-time). It looks like driver does better optimization than compiler - that can happen. As you said, it means there is definitely room for improvement, we'll look into it. Thanks for the feedback!

**Comment by Sephiroth4269** [comment] 2018-02-21 17:43
You are very welcome, my question now is that since this is the case, those numbers being real, does the miner "choose" a difficulty setting based on it's hashing abilities? If that's the case since it's a factor of a 1000 difference, does that mean that my Titan will find shares on the older version eventually at those higher hashrates? Or is it because the 9.1 architecture isn't there no matter how long I let it run it won't matter?

**Comment by dropky** [comment] 2018-02-23 08:38
You should run the version of excavator where support for Titan V was added (1.4.3 or higher). I run some tests on my local pool with lower difficulty for cryptonight and the 1.3.8 build didn't find any shares.

**Comment by Sephiroth4269** [comment] 2018-02-24 04:37
I'm aware, I looked through the algorithm on the source code, but I'm not
sure where to find out how the 9.1 CUDA cores are being integrated to find
shares? I think the difference lies somewhere between getting the algorithm
to read the hashrates that the older code provided, with the compatibility
of the 9.1 CUDA

**Comment by azazhu** [comment] 2018-03-05 06:50
@dropky, Did you mean even if 1.3.8 can achieve higher hashrate, but the function is wrong and it cannot find any shares on TitanV?

**Comment by dropky** [comment] 2018-03-05 08:36
@azazhu Yes.

**Comment by Sephiroth4269** [comment] 2018-03-05 16:14
I'm aware of that, what I'm saying is integrating the calculation that
allowed for a higher hashrate, and making it compatible for comlute level 7
devices. I am more than open to helping figure that out but I'm not sure
where to start.

I've seen several source codes for the algorithms and I'm not sure where
within there it determines CUDA type or compute level....

**Comment by azazhu** [comment] 2018-03-06 03:08
@Sephiroth4269 
there are many methods to achieve that:
1. some cuda apis allow you to check the gpu device info, 
2. generate code for every gpu arch instead of PTX.
3. implement many kenrels and auto tuning to choose kernel

**Comment by Sephiroth4269** [comment] 2018-03-06 03:11
Would you be willing to explain to me how that actually works then? I'm
trying to ask for similar help in getting the tensor core algorithms to
assist in the CUDA calculations.

My email is sephiroth4269@gmail.com

**Comment by azazhu** [comment] 2018-03-06 03:12
hi @Sephiroth4269 , I suggest you to read some public cuda program docs.

**Comment by azazhu** [comment] 2018-03-06 06:39
So the diff between 1.4.3 version and <1.4.3 version is only using different cuda compiler and their source code are same. 
For 1.4.3, it is compiled by cuda9.1. cryptoNight perf on TitanV is low, but function is correct.
For <1.4.3, it is compiler by <=cuda9.0, cryptoNight perf on TitanV is high, but function(on TitanV) is incorrect.
@dropky, do you agree my above summary?
Thanks,

**Comment by Sephiroth4269** [comment] 2018-03-06 07:37
I agree with that assessment my question is why would the different
compiling make such a massive difference and how can we circumvent that
with the different firmware to take advanrage if the previous capabilities.

Ive seen sinilar happen in reverse for my 780ti massively outproducing the
Titan V on the same algorithm with a specific compiler. I believe it is in
this thread. If not I will add it. Suffice to say we arent tapping the
potential mining power correctly when different iterations and CUDA
frameworks can create massively different hashrates.

**Comment by dropky** [comment] 2018-03-06 08:11
@azazhu You're right. Versions before 1.4.3 are compiled with CUDA 8 and don't include Volta architecture. It's actually quite interesting that it even "works" on Volta, I would expect that it would crash with an 'illegal instruction' or some similar error. 

@Sephiroth4269 It's not only compiler that is different, but also CUDA version. Keep in mind that CUDA 9 is required for Volta, my guess is that driver does the compiling from included ptx, but since it's not the correct version of CUDA and consequently not fully compatible, some, if not all kernels are actually skipped - that's why the hashrate is so much higher. 

I'll explain here quickly how the speed is measured - there is a for loop that iterates over nonces. Inside the loop there are kernels (functions that are executed on the GPU). Now let's say that 1000 nonces are processed in one iteration and that combined kernels duration is one second. That means the speed is 1kH/s. Now let's say that kernels are skipped (due to the reason explained before), the duration of one iteration could be less than 0.001 second. That means the reported speed would be 1MH/s. The reported speed is higher yes, but the speed is incorrect since the miner doesn't actually do any work. 

FYI: I completely agree with you that current implementations do not take full advantage of Titan V (not only crpytonight but other algorithms as well).

**Comment by Sephiroth4269** [comment] 2018-03-06 17:25
Thank you for the simple explanation! That being said it makes sense. That
also being said I did get errors with the other 12 algorithms. You are also
correct that the share rate was being skipped with the "higher" hashrate.

If the calculation is because cores are being skipped then thats a
different issue. From what I understand though. Is that there arent
algorithms being written by utilizing the drivers? How much different would
the algorithm look? The second question would be this: can you write an
algorithm thats universal that simply takes the existing crypto algorithm
and applies it to the new algorithm for the purpose of additional
calculation irrespective of the original crypto algorithm?

**Comment by dropky** [comment] 2018-03-11 17:33
No problem. Once again, you should use the 1.4.3 version (or more recent) of excavator where we added official support for Titan V. There shouldn't be any errors when running it.

Every architecture (Maxwell, Pascal, Volta) is different, hence the code has to be adjusted for each one to achieve the best performance. Usually the code varies a bit, even for each card (not only architecture). Not sure if I fully understand the second question.. There is no such thing as universal algorithm, every algorithm is different.

**Comment by dropky** [comment] 2018-04-03 12:51
I'm closing this since it's not a bug.

**Closed by dropky** 2018-04-03 12:51 UTC
