### ISSUE TITLE
1.5 not executing event on_quit

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#246] opened 2018-04-19 08:30 UTC
Has noticed that 1.5 began to fall at closing windows or completion on Control + C.
It seems to me that the quit event does not start
	{"event":"on_quit","commands":[
		{"id":1,"method":"device.set.tdp","params":					["0","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["0","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["0","0"]}
	]}
In the logs of the event, I do not see

**Comment by dropky** [comment] 2018-04-19 08:48
It works for me when closing with Control + C. You can add message command inside on_quit event for easier debugging:
`{"id":1,"method":"message","params":["Executing quit commands."]}`

Are you sure it doesn't work? Can you check again please?

**Comment by EvgeniyKorepov** [comment] 2018-04-19 09:35
@dropky  Added, the command is executed. So I was wrong. 
But the completion of 1.5 stably on different farms leads to a crash of the driver or the operating system. Does not depend on the current algorithm. Maybe a coincidence ...

**Comment by dropky** [comment] 2018-04-20 05:58
> But the completion of 1.5 stably on different farms leads to a crash of the driver or the operating system. 

How are you quitting excavator in this case? Force quit?  As I understand if you use quit command everything works fine? No crashes?

**Comment by EvgeniyKorepov** [comment] 2018-04-20 06:40
To close, I use the quit command via API. 
Unfortunately my request for an quiy with a parameter is not implemented yet, we have to manually hang the execution of the cmd-file (over remote VNC viewer). 
There are no crashes with this approach, everything ends well.
When closing through Control + C or closing a window, in most cases I get a driver crash or OS crash

**Comment by dropky** [comment] 2018-04-20 06:42
What version of driver do you have?

**Comment by EvgeniyKorepov** [comment] 2018-04-20 06:59
- Test stand 01 GTX 1080 driver version 391.35
- Test stand 02 GTX 1080 Ti driver version 390.65
- Test stand 03 GTX 1070 driver version 390.77

**Comment by dropky** [comment] 2018-04-20 09:30
Hm, I have 390.65 driver and can't reproduce the problem. I'll test it some more.

**Comment by EvgeniyKorepov** [comment] 2018-04-20 11:17
I forgot to mention the initial state of the excavator before going out - working algorithm with overclocking of GPU.
For example lyra2rev2 on GTX 1080 Ti TDP/CoreDelta/MemoryDelta = 120/180/-1000 - The problem is reproduced in 70% of cases.
In version 1.4.x  - the application closes correctly.
It's very strange, except for the version of the Excavator nothing changes.

**Comment by nicehashdev** [comment] 2021-01-07 07:20
This works. Closing.

**Closed by nicehashdev** 2021-01-07 07:20 UTC
